name: Flutter_Tests

on:
  push:
    tags:
      - 'v*.*.*'
  pull_request:
    branches: [main]

jobs:
  publish:
   permissions:
    id-token: write # Required for authentication using OIDC
   runs-on: ubuntu-latest
    
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.22.2
      - run: flutter --version

      - name: Restore packages
        run: flutter pub get

      - name: Check package
        run: dart pub publish --dry-run

      - name: Publish package
        run: dart pub publish --force 